package ar.com.gps.android.apps.zbasp;

public enum RdoProgram
{
	NO_HEARTBEAT, NO_IBL_RESPONSE, CANT_SWITCH_BOOTLOADER, SBL_INVALID_RESPONSE, IBL_INVALID_RESPONSE, CANT_GET_PAGESIZE, INVALID_HEX_FILE, IDX_GT_PAGESIZE, UNKOWN_REGTYPE, OTA_OK, CRC_ERROR
}
